[package]
name = "test_no_std"
version = "0.1.0"
authors = ["Alain Brenzikofer <alain.brenzikofer@scs.ch>"]
edition = "2018"


[lib]
name = "test_no_std"
crate-type = ["staticlib"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", features = ["untrusted_fs","net","backtrace"] }


[dependencies.curve25519-dalek]
git = "https://github.com/dalek-cryptography/curve25519-dalek.git"
default-features = false
features = ["u64_backend"]