[package]
name = "test_no_std"
version = "0.1.0"
authors = ["Alain Brenzikofer <alain.brenzikofer@scs.ch>"]
edition = "2018"


[lib]
name = "test_no_std"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd      = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk", features = ["untrusted_fs","net","backtrace"] }


[dependencies.schnorrkel]
git = "https://github.com/w3f/schnorrkel.git"
#branch = "schizomerlin"
features = ["preaudit_deprecated", "u64_backend"]
default-features = false
